### ISSUE TITLE
Missing documentation about PreferencesManager.save() in guide

### ISSUE THREAD

**Issue by aalmiray** [griffon-plugins/griffon-preferences-plugin#1]

**Comment by swalton00** [comment]
typo in the change I believe:

+Values of properties annotated with `@Preference` are not automatically
sincey with their

should be

+Values of properties annotated with `@Preference` are not automatically
synched with their

On Fri, Oct 9, 2015 at 8:47 AM, Andres Almiray notifications@github.com
wrote:

> Closed #1
> https://github.com/griffon-plugins/griffon-preferences-plugin/issues/1
> via 9799bfb
> https://github.com/griffon-plugins/griffon-preferences-plugin/commit/9799bfb60f4c0bc6c28204abef45852a68751e44
> .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/griffon-plugins/griffon-preferences-plugin/issues/1#event-431370364
> .

## 

Scott Walton
