### ISSUE TITLE
IllegalArgumentException in AbstractPreferencesManager

### ISSUE THREAD

**Issue by shnplr** [griffon-plugins/griffon-preferences-plugin#4]
```
convertValue(List, String, String)
```

Line 304 For the List the PropertyEditor returns PropertyEditorResolver$NoopPropertyEditor which is expected.

Line 307 throws the IllegalArgumentException because NoopPropertyEditor.value == null
i.e.

```
class PropertyEditorSupport
public void setAsText(String text) throws java.lang.IllegalArgumentException {
    if (value instanceof String) {
        setValue(text);
        return;
    }
    throw new java.lang.IllegalArgumentException(text);
}
```

The exception causes the mvcGroup not to be created so the griffon application fails at runtime. This doesn't seem to be expected behaviour for a Noop implementation.

**Comment by aalmiray** [comment]
Given that `PropertyEditorResolver` guarantees that it won't return a null value but rather an instance of a _private_ class `PropertyEditorResolver$NoopPropertyEditor` line 305 in `AbstractPreferencesManager` makes no sense now. But it also it's incapable of telling the difference between a real property editor and the noop one.

We could catch the `IllegalArgumentException` here but there's a chance we could gobble a bonafide IAE that's been thrown by a real property editor. The real solution would be to expose the `NoopPropertyEditor` class as a public one in `PropertyEditorResolver`. 

So what can be done right now in your application? Create a subclass of `DefaultPreferencesManager` that overrides the `convertValue` method, catching the IAE and returning whatever value is convenient. The next Griffon release should have a public `NoopPropertyEditor` that will make this manager work correctly for the use case you're hitting.

**Comment by aalmiray** [comment]
Fixed with https://github.com/griffon-plugins/griffon-preferences-plugin/commit/984092a1e68ef446e7be248dd858de4dc93c74ab
